package com.eshwar.rideconnectx.data.local.db

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * A single in-app notification.
 *
 * These are generated by the app itself (service reminders, pairing results,
 * ride summaries) rather than pushed from a server, so the list works offline
 * and survives reinstall-free upgrades via Room.
 */
@Entity(tableName = "notifications", indices = [Index(value = ["ownerId"])])
data class NotificationEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,

    /**
     * The Google account this row belongs to, or [OwnerScope.GUEST].
     *
     * Every query filters on it. Two accounts share one database file, and
     * before this column existed the second person to sign in on a phone saw
     * the first person's rows — their emergency contact, their rides, their
     * service history. No default: the compiler has to point at every write
     * site, because a row saved under the wrong owner is the bug this prevents.
     */
    val ownerId: String,

    /** Epoch millis — also the sort key, newest first. */
    val createdAt: Long,

    val title: String,
    val body: String,

    /** Drives the icon, accent colour and where a tap leads. */
    val kind: NotificationKind,

    val unread: Boolean = true,
)

/**
 * The categories the design gives distinct icons and accent colours to.
 * Stored by name, so adding a case never renumbers the existing rows.
 */
enum class NotificationKind {
    SERVICE,
    VEHICLE,
    RIDE,
    SAFETY,
    SYSTEM,
}
