package com.eshwar.rideconnectx.data.remote

import android.app.Activity
import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.eshwar.rideconnectx.R
import com.eshwar.rideconnectx.domain.model.AuthError
import com.eshwar.rideconnectx.domain.model.AuthResult
import com.eshwar.rideconnectx.domain.model.LoginMethod
import com.eshwar.rideconnectx.domain.model.UserSession
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.android.libraries.identity.googleid.GoogleIdTokenParsingException
import com.google.firebase.auth.EmailAuthProvider
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseAuthInvalidCredentialsException
import com.google.firebase.auth.FirebaseAuthInvalidUserException
import com.google.firebase.auth.FirebaseAuthUserCollisionException
import com.google.firebase.auth.FirebaseAuthWeakPasswordException
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.auth.ktx.userProfileChangeRequest
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await
import java.io.IOException
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class FirebaseAuthDataSource @Inject constructor(
    @ApplicationContext private val context: Context,
    private val auth: FirebaseAuth,
) {

    /**
     * Emits on every Firebase auth transition, including the restore that
     * happens at cold start. This is what makes auto-login work.
     */
    val authStateChanges: Flow<FirebaseUser?> = callbackFlow {
        val listener = FirebaseAuth.AuthStateListener { trySend(it.currentUser) }
        auth.addAuthStateListener(listener)
        awaitClose { auth.removeAuthStateListener(listener) }
    }

    val currentUser: FirebaseUser? get() = auth.currentUser

    /**
     * Generated by the google-services plugin from the `client_type: 3` entry.
     * Absent when Google Sign-In was enabled after the config file was downloaded.
     */
    private val webClientId: String?
        get() = (
            context.resources
                .getIdentifier("default_web_client_id", "string", context.packageName)
                .takeIf { it != 0 }
                ?.let(context::getString)
                ?.takeIf { it.isNotBlank() }
                ?: context.getString(R.string.google_oauth_client_id).takeIf { it.isNotBlank() }
            )

    val isGoogleSignInAvailable: Boolean get() = webClientId != null

    /**
     * Google sign-in through Credential Manager.
     *
     * **Why this is two passes.** The first tap used to report "no Google
     * accounts found" on a phone with ten of them, and only the second or third
     * tap showed the picker. Two things caused it, and both are fixed here:
     *
     * 1. `setAutoSelectEnabled(true)` asks for a *silent* sign-in. With no
     *    previously authorised credential there is nothing to select silently,
     *    and Credential Manager answers `NoCredentialException` rather than
     *    showing UI. It is off now — this screen is an explicit tap on
     *    "Continue with Google", so the rider has already asked to choose.
     * 2. A single pass cannot serve both cases. Google's own guidance is to ask
     *    for **authorised accounts first** (instant for a returning rider) and,
     *    only when that finds nothing, ask again with the filter off to show
     *    every account on the device.
     *
     * "No accounts" is therefore only reported after *both* passes come back
     * empty, which on a phone with accounts cannot happen.
     */
    suspend fun signInWithGoogle(activity: Activity): AuthResult {
        val idToken = googleIdToken(activity).getOrElse { return it.asFailure() }
        return signInWithFirebase(GoogleAuthProvider.getCredential(idToken, null))
    }

    /** Carries an [AuthError] out of [googleIdToken] through a [Result]. */
    private class AuthErrorException(val error: AuthError) : Exception()

    private fun Throwable.asFailure() =
        AuthResult.Failure((this as? AuthErrorException)?.error ?: toAuthError())

    /** Authorised accounts first, then every account — see [signInWithGoogle]. */
    private suspend fun googleIdToken(activity: Activity): Result<String> {
        val clientId = webClientId
            ?: return Result.failure(AuthErrorException(AuthError.WebClientIdMissing))
        val credentialManager = CredentialManager.create(activity)
        return try {
            val token = requestGoogleIdToken(
                credentialManager, activity, clientId, authorizedOnly = true,
            ) ?: requestGoogleIdToken(
                credentialManager, activity, clientId, authorizedOnly = false,
            )
            token?.let { Result.success(it) }
                ?: Result.failure(AuthErrorException(AuthError.NoCredentialAvailable))
        } catch (e: GetCredentialCancellationException) {
            Result.failure(AuthErrorException(AuthError.Cancelled))
        } catch (e: GoogleIdTokenParsingException) {
            Result.failure(AuthErrorException(AuthError.TokenFailure(e.message.orEmpty())))
        } catch (e: GetCredentialException) {
            Result.failure(AuthErrorException(AuthError.TokenFailure(e.message.orEmpty())))
        }
    }

    /**
     * Firebase refuses to delete an account unless the sign-in is fresh, so
     * the rider proves it is them again first. Picking a *different* Google
     * account here fails - Firebase checks it is the same user.
     */
    suspend fun reauthenticateWithGoogle(activity: Activity): AuthResult {
        val user = auth.currentUser
            ?: return AuthResult.Failure(AuthError.Unknown("You're not signed in."))
        // Silent first: auto-select the account already authorised for this app,
        // so the rider is not shown a sign-in picker just to confirm a delete
        // (rider, 21 Sep). The picker appears only if the silent pass fails.
        val silent = webClientId?.let { clientId ->
            runCatching {
                requestGoogleIdToken(
                    CredentialManager.create(activity), activity, clientId,
                    authorizedOnly = true, autoSelect = true,
                )
            }.getOrNull()
        }
        val idToken = silent ?: googleIdToken(activity).getOrElse { return it.asFailure() }
        return runCatching {
            user.reauthenticate(GoogleAuthProvider.getCredential(idToken, null)).await()
            AuthResult.Success(user.toSession(LoginMethod.GOOGLE))
        }.getOrElse { AuthResult.Failure(it.toAuthError()) }
    }

    suspend fun reauthenticateWithPassword(password: String): AuthResult {
        val user = auth.currentUser
            ?: return AuthResult.Failure(AuthError.Unknown("You're not signed in."))
        val email = user.email
            ?: return AuthResult.Failure(AuthError.Unknown("This account has no email."))
        return runCatching {
            user.reauthenticate(EmailAuthProvider.getCredential(email, password)).await()
            AuthResult.Success(user.toSession(LoginMethod.EMAIL))
        }.getOrElse { AuthResult.Failure(it.toAuthError()) }
    }

    /**
     * One Credential Manager pass.
     *
     * @return the id token, or null when this pass found no credential —
     *         which the caller treats as "try the other pass", not as failure.
     *         Cancellation and real errors still throw.
     */
    private suspend fun requestGoogleIdToken(
        credentialManager: CredentialManager,
        activity: Activity,
        clientId: String,
        authorizedOnly: Boolean,
        autoSelect: Boolean = false,
    ): String? {
        val request = GetCredentialRequest.Builder()
            .addCredentialOption(
                GetGoogleIdOption.Builder()
                    .setFilterByAuthorizedAccounts(authorizedOnly)
                    .setServerClientId(clientId)
                    // Off for sign-in (see signInWithGoogle); on only for the
                    // silent re-check before deleting an account.
                    .setAutoSelectEnabled(autoSelect)
                    .build()
            )
            .build()

        val credential = try {
            credentialManager.getCredential(activity, request).credential
        } catch (e: NoCredentialException) {
            return null
        }

        if (credential !is CustomCredential ||
            credential.type != GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
        ) {
            throw GoogleIdTokenParsingException(
                IllegalStateException("Unexpected credential type: ${credential.type}")
            )
        }

        return GoogleIdTokenCredential.createFrom(credential.data).idToken
    }

    private suspend fun signInWithFirebase(
        credential: com.google.firebase.auth.AuthCredential,
    ): AuthResult = runCatching {
        val user = auth.signInWithCredential(credential).await().user
            ?: return AuthResult.Failure(AuthError.Unknown("Firebase returned no user."))
        AuthResult.Success(user.toSession(LoginMethod.GOOGLE))
    }.getOrElse { AuthResult.Failure(it.toAuthError()) }

    suspend fun signUpWithEmail(email: String, password: String, name: String): AuthResult =
        runCatching {
            val user = auth.createUserWithEmailAndPassword(email.trim(), password).await().user
                ?: return AuthResult.Failure(AuthError.Unknown("Firebase returned no user."))
            user.updateProfile(userProfileChangeRequest { displayName = name.trim() }).await()
            AuthResult.Success(user.toSession(LoginMethod.EMAIL).copy(name = name.trim()))
        }.getOrElse { AuthResult.Failure(it.toAuthError()) }

    suspend fun signInWithEmail(email: String, password: String): AuthResult =
        runCatching {
            val user = auth.signInWithEmailAndPassword(email.trim(), password).await().user
                ?: return AuthResult.Failure(AuthError.Unknown("Firebase returned no user."))
            AuthResult.Success(user.toSession(LoginMethod.EMAIL))
        }.getOrElse { AuthResult.Failure(it.toAuthError()) }

    suspend fun sendPasswordReset(email: String): AuthResult = runCatching {
        auth.sendPasswordResetEmail(email.trim()).await()
        AuthResult.Success(UserSession())
    }.getOrElse { AuthResult.Failure(it.toAuthError()) }

    /**
     * Clears the Firebase session and the Credential Manager state, so the next
     * sign-in shows the account picker instead of silently reusing the last one.
     */
    suspend fun signOut(context: Context) {
        auth.signOut()
        runCatching {
            CredentialManager.create(context).clearCredentialState(
                androidx.credentials.ClearCredentialStateRequest()
            )
        }
    }

    suspend fun deleteAccount(): AuthResult = runCatching {
        val user = auth.currentUser
            ?: return AuthResult.Failure(AuthError.Unknown("You're not signed in."))
        user.delete().await()
        AuthResult.Success(UserSession())
    }.getOrElse { AuthResult.Failure(it.toAuthError()) }

    fun FirebaseUser.toSession(method: LoginMethod) = UserSession(
        name = displayName.orEmpty(),
        email = email.orEmpty(),
        method = method,
        uid = uid,
        phone = phoneNumber.orEmpty(),
        photoUrl = photoUrl?.toString().orEmpty(),
    )

    private fun Throwable.toAuthError(): AuthError = when (this) {
        is IOException -> AuthError.NoInternet
        is FirebaseAuthWeakPasswordException ->
            AuthError.WeakPassword("Password must be at least 6 characters.")
        is FirebaseAuthUserCollisionException ->
            AuthError.AccountExists("An account already exists with that email.")
        is FirebaseAuthInvalidCredentialsException ->
            AuthError.InvalidCredentials("That email or password isn't right.")
        is FirebaseAuthInvalidUserException ->
            AuthError.InvalidCredentials("No account found for that email.")
        else -> {
            val msg = message.orEmpty()
            if (msg.contains("network", ignoreCase = true)) AuthError.NoInternet
            else AuthError.Unknown(msg.ifBlank { "Something went wrong. Please try again." })
        }
    }
}
